apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-chat
  template:
    metadata:
      labels:
        app: mongo-chat
    spec:
      containers:
        - name: mongo-chat
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-chat-data
              mountPath: /data/db
      volumes:
        - name: mongo-chat-data
          persistentVolumeClaim:
            claimName: mongo-chat-pvc
