apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: server
          image: jdk2py/server:latest
          env:
            - name: MONGODB_URL
              value: "mongodb://mongo:27017/my-chat-app"
            - name: PORT
              value: "4000"
            - name: JWT_SECRET
              value: "mysecretkey"
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 31001  # Specify the port on each node where this service can be accessed
  selector:
    app: backend
