# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: jdk2py/backend:latest
          env:
            - name: MONGODB_URL
              value: "mongodb+srv://julihocastillo:vQI7ZpG2ml13Tyib@cluster0.mjrfzla.mongodb.net/?retryWrites=true&w=majority"
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-atlas-credentials
                  key: password
            - name: PORT
              value: "4000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
          ports:
            - containerPort: 4000

# Backend Service
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: backend

# Frontend Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jdk2py/frontend:latest
          env:
            - name: REACT_APP_BACKEND_HTTP_URL
              value: "http://a6bd7ac91d4f4411bb76e38fe6ac53be-a25919179c5b392e.elb.us-east-1.amazonaws.com/api"
            - name: REACT_APP_BACKEND_WS_URL
              value: "ws://a6bd7ac91d4f4411bb76e38fe6ac53be-a25919179c5b392e.elb.us-east-1.amazonaws.com/api"
            - name: PUBLIC_URL
              value: "/frontend"
          ports:
            - containerPort: 3000

# Frontend Service
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend

# Ingress Resource
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  ingressClassName: "nginx"
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 4000
