#docker-compose.yml
version: "3.0"

services:
  client:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: todo-mern-crud-graphql-frontend
    ports:
      - 3000:3000
    networks:
      - todo-mern-crud-graphql-network
    volumes:
      - ./frontend/src:/usr/app/src
      - ./frontend/public:/usr/app/public
    depends_on:
      - server
    env_file: frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  server:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: todo-mern-crud-graphql-backend
    ports:
      - 4000:4000
    networks:
      - todo-mern-crud-graphql-network
    volumes:
      - ./backend/src:/usr/app/src
    depends_on:
      - db
    env_file: backend/.env

  db:
    image: mongo
    container_name: todo-mern-graphql-mongodb
    ports:
      - 27017:27017
    networks:
      - todo-mern-crud-graphql-network
    volumes:
      - mongo-data:/data/db

networks:
  todo-mern-crud-graphql-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
