apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-chat
  template:
    metadata:
      labels:
        app: mongo-chat
    spec:
      containers:
        - name: mongo-chat
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-chat-data
              mountPath: /data/db
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: mongo-chat-data
          persistentVolumeClaim:
            claimName: mongo-chat-pvc
