version: '2.1'

services:
  auth_service:
    build:
      context: ./authService
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=mysecretkey
      - MONGODB_URL=mongodb://mongo:27017/authService
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - JWT_SECRET=mysecretkey
      - MONGODB_URL=mongodb://mongo:27017/backend
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  chat_service:
    build:
      context: ./chatService
      dockerfile: Dockerfile
    ports:
      - "4500:4500"
    environment:
      - PORT=4500
      - JWT_SECRET=mysecretkey
      - MONGODB_URL=mongodb://mongo:27017/chatService
      - RABBITMQ_URL=amqp://user:password@rabbitm:5672
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_HTTP_URL=http://localhost:4000
      - REACT_APP_BACKEND_WS_URL=ws://localhost:4000
      - REACT_APP_AUTH_SERVICE_HTTP_URL=http://localhost:5000
      - REACT_APP_AUTH_SERVICE_WS_URL=ws://localhost:5000
      - REACT_APP_CHAT_SERVICE_HTTP_URL=http://localhost:4500
      - REACT_APP_CHAT_SERVICE_WS_URL=ws://localhost:4500

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: "rabbitmq:management"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 30s
      retries: 5

volumes:
  mongo-data:
  rabbitmq_data:
