# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contactService
  template:
    metadata:
      labels:
        app: contactService
    spec:
      containers:
        - name: contactService
          image: jdk2py/contactService:latest
          env:
            - name: MONGODB_URL
              value: "mongodb://mongodb:27017"
            - name: PORT
              value: "4000"
            - name: JWT_SECRET
              value: "mysecretkey"
          ports:
            - containerPort: 4000

# Backend Service
---
apiVersion: v1
kind: Service
metadata:
  name: contactService
spec:
  type: LoadBalancer
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: contactService
