apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jdk2py/frontend:latest
          env:
            - name: REACT_APP_CONTACT_SERVICE_HTTP_URL
              value: "http://localhost:3001"
            - name: REACT_APP_CONTACT_SERVICE_WS_URL
              value: "ws://localhost:3001"
          ports:
            - containerPort: 3000