apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: jdk2py/gateway:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: CONTACT_SERVICE_URL
              value: "http://contact-service:4000"
            - name: CHAT_SERVICE_URL
              value: "http://chat-service:4500"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:5000"